// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FloppyServerClient is the client API for FloppyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FloppyServerClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type floppyServerClient struct {
	cc grpc.ClientConnInterface
}

func NewFloppyServerClient(cc grpc.ClientConnInterface) FloppyServerClient {
	return &floppyServerClient{cc}
}

func (c *floppyServerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/floppy.FloppyServer/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FloppyServerServer is the server API for FloppyServer service.
// All implementations should embed UnimplementedFloppyServerServer
// for forward compatibility
type FloppyServerServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedFloppyServerServer should be embedded to have forward compatible implementations.
type UnimplementedFloppyServerServer struct {
}

func (UnimplementedFloppyServerServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

// UnsafeFloppyServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FloppyServerServer will
// result in compilation errors.
type UnsafeFloppyServerServer interface {
	mustEmbedUnimplementedFloppyServerServer()
}

func RegisterFloppyServerServer(s grpc.ServiceRegistrar, srv FloppyServerServer) {
	s.RegisterService(&FloppyServer_ServiceDesc, srv)
}

func _FloppyServer_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloppyServerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/floppy.FloppyServer/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloppyServerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FloppyServer_ServiceDesc is the grpc.ServiceDesc for FloppyServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FloppyServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "floppy.FloppyServer",
	HandlerType: (*FloppyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _FloppyServer_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "floppy.proto",
}
